server:
  port: 8888

spring:
  application:
      name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/giantfoot/SpringcloudConfig/
          searchPaths: respo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
#spring.cloud.config.server.git.username=your username
#spring.cloud.config.server.git.password=your password
